---
lang: ar
dir: rtl
toc-title: "المحتويات"
title: "كتاب استيعاب الوجوه الممكنة في صنعة الأسطرلاب"
subtitle: "لأبي الريحان محمد بن أحمد البيروني (٣٦٢ – بعد ٤٤٠ هـ / ٩٧٣ – بعد ١٠٤٨ م): دراسة، وإعادة رسم أشكاله الخمسة والثمانين بالحساب الهندسي، مع معادلاتها والتعليق عليها"
author: "اعتمادًا على نسخة المكتبة البريطانية Or 5593"
---
